services:
  service-api:
    container_name: service-api
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION:-22.12.0}
        - PORT=${PORT:-3000}
    command: npm run start:api:dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - ./:/app